<h1>EDIT YOUR PROFILE</h1>


<p class= "content" >
<form method="post" action="/profile/edit" class="form"><br>
    <label>PSEUDO</label>    <input type="text" value= <?php echo "".$_SESSION['pseudo'] ?> name="pseudo" placeholder="Nicolas"> <br><br>
    <label>DESCRIPTION</label>    <input type="text" name="description" placeholder="Dupont"> <br><br>
    <label>WEBSITE</label>    <input type="text" name="website" placeholder="www.dupontnicolas.fr"> <br><br>
	<br><br>
    <input type="submit" class="classe_button" value="Edit">

</form> <br>

</p>